# Generated by Django 3.0.3 on 2020-02-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0002_auto_20200211_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_name',
        ),
    ]
