# Generated by Django 3.0.3 on 2020-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0003_remove_movie_director_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.CharField(default='No information available', max_length=500),
        ),
        migrations.AddField(
            model_name='director',
            name='photo_url',
            field=models.CharField(default='No Image Available', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='photo_url',
            field=models.CharField(default='No Image Available', max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='nationality',
            field=models.CharField(default='USA', max_length=100),
        ),
    ]
